# ===============================
# Настройки базы данных
# ===============================
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/bankdb
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  # ===============================
  # Настройки JPA / Hibernate
  # ===============================
  jpa:
    hibernate:
      ddl-auto: update        # Liquibase управляет схемой
    show-sql: true
    properties:
      hibernate.format_sql: true

  # ===============================
  # Настройки Liquibase
  # ===============================
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml
    contexts: development
    default-schema: public
    drop-first: false
    enabled: true

# ===============================
# Настройки сервера
# ===============================
server:
  port: 8080
